# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Festival of Neighbourhoods'
tagline:          'City of Kitchener, 2015'
description:      'Creating connections, growing traditions!'
url:              http://graymo.github.io/FON
baseurl:          '/FON'

author:
  name:           'Graeme Ruck'
  url:            http://waterlooregion.org

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/graymo/FON
